title: Vibey-Jekyll
description: ただのネタ帳です。
baseurl: "/Vibey-Jekyll"
url: "https://anya.github.io"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
